import { isMainThread } from "worker_threads";
import { Album, AlbumEntry, AlbumEntryMetaData } from "../../../shared/types/types";
import { getWorker } from "../../worker-manager";
import { getWalkerDatabase } from "./database";
import * as picasaIni from "./picasa-ini";
import { WorkerAdaptor } from "../../../shared/rpc-transport/worker-adaptor";

/**
 * Walker Service Mutations
 * 
 * These functions perform write operations that update both the database and picasa-ini files.
 * In the main thread, they use the generated RPC client to call the worker.
 * In the worker thread, they perform the actual operations.
 */

// Client instance (lazy initialized in main thread)
let walkerWorkerClient: any = null;

/**
 * Get or create the walker worker RPC client
 */
async function getWalkerWorkerClient(): Promise<any> {
  if (!isMainThread) {
    throw new Error("getWalkerWorkerClient should only be called from main thread");
  }

  if (!walkerWorkerClient) {
    const worker = getWorker('walker');
    if (!worker) {
      throw new Error("Walker worker not available");
    }

    const adaptor = new WorkerAdaptor(worker);
    // Import generated client (generated by npm run build:rpc)
    const { WalkerWorkerClient } = await import("../../../client/rpc/generated-rpc/WalkerWorkerClient");
    walkerWorkerClient = new WalkerWorkerClient();
    await walkerWorkerClient.initialize(adaptor);
  }

  return walkerWorkerClient;
}

/**
 * Update entry metadata in both database and picasa-ini
 */
export async function updateEntryMetadata(
  entry: AlbumEntry,
  metadata: AlbumEntryMetaData
): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.updateEntryMetadata(entry, metadata);
  } else {
    // Worker thread: perform the actual operation
    const db = getWalkerDatabase();
    const dbPromise = new Promise<void>((resolve, reject) => {
      try {
        db.updateEntryMetadata(entry, metadata);
        resolve();
      } catch (error) {
        reject(error);
      }
    });

    // Update picasa-ini
    const picasaPromise = picasaIni.updatePicasaEntry(entry, "*", metadata);

    // Wait for both to complete
    await Promise.all([dbPromise, picasaPromise]);
  }
}

/**
 * Update a specific field in entry metadata
 */
export async function updatePicasaEntry(
  entry: AlbumEntry,
  field: keyof AlbumEntryMetaData | "*",
  value: any
): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.updatePicasaEntry(entry, field as string, value);
  } else {
    // Worker thread: perform the actual operation
    // First get current metadata
    const db = getWalkerDatabase();
    const currentMetadata = db.getEntryMetadata(entry);

    // Update the field
    let updatedMetadata: AlbumEntryMetaData;
    if (field === "*") {
      updatedMetadata = value || {};
    } else {
      updatedMetadata = { ...currentMetadata };
      if (value !== undefined && value !== null) {
        (updatedMetadata as any)[field] = `${value}`;
      } else {
        delete (updatedMetadata as any)[field];
      }
    }

    // Update database
    const dbPromise = new Promise<void>((resolve, reject) => {
      try {
        db.updateEntryMetadata(entry, updatedMetadata);
        resolve();
      } catch (error) {
        reject(error);
      }
    });

    // Update picasa-ini
    const picasaPromise = picasaIni.updatePicasaEntry(entry, field, value);

    // Wait for both to complete
    await Promise.all([dbPromise, picasaPromise]);
  }
}

/**
 * Set caption for an entry
 */
export async function setCaption(entry: AlbumEntry, caption: string): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.setCaption(entry, caption);
  } else {
    await updatePicasaEntry(entry, 'caption', caption);
    await picasaIni.setCaption(entry, caption);
  }
}

/**
 * Set filters for an entry
 */
export async function setFilters(entry: AlbumEntry, filters: string): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.setFilters(entry, filters);
  } else {
    await updatePicasaEntry(entry, 'filters', filters);
    await picasaIni.setFilters(entry, filters);
  }
}

/**
 * Set rotate for an entry
 */
export async function setRotate(entry: AlbumEntry, rotate?: string): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.setRotate(entry, rotate);
  } else {
    await updatePicasaEntry(entry, 'rotate', rotate);
    await picasaIni.setRotate(entry, rotate);
  }
}

/**
 * Toggle star for entries
 */
export async function toggleStar(entries: AlbumEntry[]): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.toggleStar(entries);
  } else {
    await picasaIni.toggleStar(entries);
    // Also update database for each entry
    const db = getWalkerDatabase();
    for (const entry of entries) {
      const metadata = await picasaIni.getPicasaEntry(entry);
      db.updateEntryMetadata(entry, metadata);
    }
  }
}

/**
 * Rotate entries
 */
export async function rotate(entries: AlbumEntry[], direction: string): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.rotate(entries, direction);
  } else {
    await picasaIni.rotate(entries, direction);
    // Also update database for each entry
    const db = getWalkerDatabase();
    for (const entry of entries) {
      const metadata = await picasaIni.getPicasaEntry(entry);
      db.updateEntryMetadata(entry, metadata);
    }
  }
}

/**
 * Set album shortcut
 */
export async function setPicasaAlbumShortcut(album: Album, shortcut: string): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.setPicasaAlbumShortcut(album, shortcut);
  } else {
    await picasaIni.setPicasaAlbumShortcut(album, shortcut);
  }
}

/**
 * Touch picasa entry (ensure it exists in picasa-ini)
 */
export async function touchPicasaEntry(entry: AlbumEntry): Promise<void> {
  if (isMainThread) {
    const client = await getWalkerWorkerClient();
    return await client.touchPicasaEntry(entry);
  } else {
    await picasaIni.touchPicasaEntry(entry);
    // Also update database
    const db = getWalkerDatabase();
    const metadata = await picasaIni.getPicasaEntry(entry);
    db.updateEntryMetadata(entry, metadata);
  }
}
