export const TSCodeTemplate = `
/* This file is automatically generated, do not edit it */
/* This file is generated from the template located here : ${__dirname} */
<<CONSTANTS>>
export class <<CLASS>> {
  private transport_?: any;
  initialize(transport: any): void {
    this.transport_ = transport;
  }

  public on(event: string, cb: Function): Function {
    return this.transport_.on(event, cb);
  }

  // @ts-ignore
  private async emitNoPayload(command: string, payload: any): Promise<void> {
    return this.emit(command, payload);
  }

  private async emit(command: string, payload: any): Promise<any> {
    return new Promise((resolve, reject) =>
      this.transport_.emit(command, payload, (error:string, response:string) => {
        if (error) {
          reject(error);
        } else {
          resolve(response);
        }
      })
    );
  }
<<CODE>>
}`;
