
/* This file is automatically generated, do not edit it */
/* This file is generated from the template located here : /Users/turpault/dev/my-picasa/dist/server/rpc */
/* Generation date : 2021-11-01T02:50:16.471Z */
export enum Exceptions {  NotAtTip = "NotAtTip",
  ShaNotInBranch = "ShaNotInBranch",
  NotInitialized = "NotInitialized",
  NotAKey = "NotAKey",
  TagNotFound = "TagNotFound",
  TagAlreadyExists = "TagAlreadyExists",
  FailedPublishAndTag = "FailedPublishAndTag",
  FailedResetStream = "FailedResetStream",
}

export class MyPicasa {
  private socket_?: any;
  async initialize(socket: any): Promise<void> {
    this.socket_ = socket;
  }

  // @ts-ignore
  private async emitNoPayload(command: string, payload: any): Promise<void> {
    return this.emit(command, payload);
  }

  private async emit(command: string, payload: any): Promise<any> {
    return new Promise((resolve, reject) =>
      this.socket_.emit(command, payload, (error:string, response:string) => {
        if (error) {
          reject(error);
        } else {
          resolve(response);
        }
      })
    );
  }

  async buildContext(fileName: string):Promise<any> {
    return this.emit('MyPicasa:buildContext', {
      'args': { fileName } 
    });
  }
  async cloneContext(context: string):Promise<any> {
    return this.emit('MyPicasa:cloneContext', {
      'args': { context } 
    });
  }
  async destroyContext(context: string):Promise<any> {
    return this.emit('MyPicasa:destroyContext', {
      'args': { context } 
    });
  }
  async transform(context: string, operations: string):Promise<any> {
    return this.emit('MyPicasa:transform', {
      'args': { context, operations } 
    });
  }
  async setOptions(context: string, options: object):Promise<any> {
    return this.emit('MyPicasa:setOptions', {
      'args': { context, options } 
    });
  }
  async execute(context: string, operations: object):Promise<any> {
    return this.emit('MyPicasa:execute', {
      'args': { context, operations } 
    });
  }
  async encode(context: string):Promise<any> {
    return this.emit('MyPicasa:encode', {
      'args': { context } 
    });
  }
  async getJob(hash: object):Promise<any> {
    return this.emit('MyPicasa:getJob', {
      'args': { hash } 
    });
  }
  async createJob(jobName: string, jobData: object):Promise<any> {
    return this.emit('MyPicasa:createJob', {
      'args': { jobName, jobData } 
    });
  }
  async folders():Promise<any> {
    return this.emit('MyPicasa:folders', {
      'args': {  } 
    });
  }
  async readFileContents(file: string):Promise<any> {
    return this.emit('MyPicasa:readFileContents', {
      'args': { file } 
    });
  }
  async writeFileContents(file: string, data: object):Promise<any> {
    return this.emit('MyPicasa:writeFileContents', {
      'args': { file, data } 
    });
  }
  async folder(folder: string):Promise<any> {
    return this.emit('MyPicasa:folder', {
      'args': { folder } 
    });
  }
}