import { Filters } from "../../../shared/types/types";

/* This file is automatically generated, do not edit it */
/* This file is generated from the template located here : /Users/turpault/dev/picisa/server/rpc */
export enum Exceptions {}

export class PicisaClient {
  private transport_?: any;
  initialize(transport: any): void {
    this.transport_ = transport;
  }

  public on(event: string, cb: Function): Function {
    return this.transport_.on(event, cb);
  }

  // @ts-ignore
  private async emitNoPayload(command: string, payload: any): Promise<void> {
    return this.emit(command, payload);
  }

  private async emit(command: string, payload: any): Promise<any> {
    return new Promise((resolve, reject) =>
      this.transport_.emit(command, payload, (error:string, response:string) => {
        if (error) {
          reject(error);
        } else {
          resolve(response);
        }
      })
    );
  }

  async buildContext(entry:object):Promise<any> {
    return this.emit('PicisaClient:buildContext', {
      'args': { entry } 
    });
  }
  async cloneContext(context:string, hint:string):Promise<any> {
    return this.emit('PicisaClient:cloneContext', {
      'args': { context, hint } 
    });
  }
  async destroyContext(context:string):Promise<any> {
    return this.emit('PicisaClient:destroyContext', {
      'args': { context } 
    });
  }
  async transform(context:string, operations:string):Promise<any> {
    return this.emit('PicisaClient:transform', {
      'args': { context, operations } 
    });
  }
  async setOptions(context:string, options:object):Promise<any> {
    return this.emit('PicisaClient:setOptions', {
      'args': { context, options } 
    });
  }
  async execute(context:string, operations:object):Promise<any> {
    return this.emit('PicisaClient:execute', {
      'args': { context, operations } 
    });
  }
  async commit(context:string):Promise<any> {
    return this.emit('PicisaClient:commit', {
      'args': { context } 
    });
  }
  async encode(context:string, mime:string, format:string):Promise<any> {
    return this.emit('PicisaClient:encode', {
      'args': { context, mime, format } 
    });
  }
  async getJob(hash:string):Promise<any> {
    return this.emit('PicisaClient:getJob', {
      'args': { hash } 
    });
  }
  async waitJob(hash:string):Promise<any> {
    return this.emit('PicisaClient:waitJob', {
      'args': { hash } 
    });
  }
  async createJob(jobName:string, jobData:object):Promise<any> {
    return this.emit('PicisaClient:createJob', {
      'args': { jobName, jobData } 
    });
  }
  async folders(filters?:Filters):Promise<any> {
    return this.emit('PicisaClient:folders', {
      'args': { filters } 
    });
  }
  async media(album:object, filters?:Filters):Promise<any> {
    return this.emit('PicisaClient:media', {
      'args': { album, filters } 
    });
  }
  async mediaCount(album:object, filters?:Filters):Promise<any> {
    return this.emit('PicisaClient:mediaCount', {
      'args': { album, filters } 
    });
  }
  async getFileContents(file:string):Promise<any> {
    return this.emit('PicisaClient:getFileContents', {
      'args': { file } 
    });
  }
  async writeFileContents(file:string, data:string):Promise<any> {
    return this.emit('PicisaClient:writeFileContents', {
      'args': { file, data } 
    });
  }
  async folder(folder:string):Promise<any> {
    return this.emit('PicisaClient:folder', {
      'args': { folder } 
    });
  }
  async sortAlbum(album:object, sort:string):Promise<any> {
    return this.emit('PicisaClient:sortAlbum', {
      'args': { album, sort } 
    });
  }
  async setRank(entry:string, rank:number):Promise<any> {
    return this.emit('PicisaClient:setRank', {
      'args': { entry, rank } 
    });
  }
  async getAlbumMetadata(album:object):Promise<any> {
    return this.emit('PicisaClient:getAlbumMetadata', {
      'args': { album } 
    });
  }
  async getAlbumEntryMetadata(albumEntry:object):Promise<any> {
    return this.emit('PicisaClient:getAlbumEntryMetadata', {
      'args': { albumEntry } 
    });
  }
  async getExifData(entry:object):Promise<any> {
    return this.emit('PicisaClient:getExifData', {
      'args': { entry } 
    });
  }
  async getFileStats(entry:object):Promise<any> {
    return this.emit('PicisaClient:getFileStats', {
      'args': { entry } 
    });
  }
  async geoPOI(entry:object):Promise<any> {
    return this.emit('PicisaClient:geoPOI', {
      'args': { entry } 
    });
  }
  async getExifCoordinates(entry:object):Promise<any> {
    return this.emit('PicisaClient:getExifCoordinates', {
      'args': { entry } 
    });
  }
  async getPicasaEntry(entry:object):Promise<any> {
    return this.emit('PicisaClient:getPicasaEntry', {
      'args': { entry } 
    });
  }
  async setFilters(entry:object, filters:string):Promise<any> {
    return this.emit('PicisaClient:setFilters', {
      'args': { entry, filters } 
    });
  }
  async setCaption(entry:object, caption:string):Promise<any> {
    return this.emit('PicisaClient:setCaption', {
      'args': { entry, caption } 
    });
  }
  async makeAlbum(name:string):Promise<any> {
    return this.emit('PicisaClient:makeAlbum', {
      'args': { name } 
    });
  }
  async openInFinder(album:object):Promise<any> {
    return this.emit('PicisaClient:openInFinder', {
      'args': { album } 
    });
  }
  async openEntryInFinder(entry:object):Promise<any> {
    return this.emit('PicisaClient:openEntryInFinder', {
      'args': { entry } 
    });
  }
  async undoList():Promise<any> {
    return this.emit('PicisaClient:undoList', {
      'args': {  } 
    });
  }
  async undo(id:string):Promise<any> {
    return this.emit('PicisaClient:undo', {
      'args': { id } 
    });
  }
  async imageInfo(entry:object):Promise<any> {
    return this.emit('PicisaClient:imageInfo', {
      'args': { entry } 
    });
  }
  async albumEntriesWithMetadataAndExif(entries:object[]):Promise<any> {
    return this.emit('PicisaClient:albumEntriesWithMetadataAndExif', {
      'args': { entries } 
    });
  }
  async log(event:string, data:object):Promise<any> {
    return this.emit('PicisaClient:log', {
      'args': { event, data } 
    });
  }
  async exception(message:string, file:string, line:number, col:number, error:object):Promise<any> {
    return this.emit('PicisaClient:exception', {
      'args': { message, file, line, col, error } 
    });
  }
  async ready():Promise<any> {
    return this.emit('PicisaClient:ready', {
      'args': {  } 
    });
  }
  async getFilterList(group:string):Promise<any> {
    return this.emit('PicisaClient:getFilterList', {
      'args': { group } 
    });
  }
  async getConvolutionKernelNames():Promise<any> {
    return this.emit('PicisaClient:getConvolutionKernelNames', {
      'args': {  } 
    });
  }
  async getFilterGroups():Promise<any> {
    return this.emit('PicisaClient:getFilterGroups', {
      'args': {  } 
    });
  }
  async setAlbumShortcut(album:object, shortcut:string):Promise<any> {
    return this.emit('PicisaClient:setAlbumShortcut', {
      'args': { album, shortcut } 
    });
  }
  async getShortcuts():Promise<any> {
    return this.emit('PicisaClient:getShortcuts', {
      'args': {  } 
    });
  }
  async getSourceEntry(entry:object):Promise<any> {
    return this.emit('PicisaClient:getSourceEntry', {
      'args': { entry } 
    });
  }
  async rotate(entries:object, direction:string):Promise<any> {
    return this.emit('PicisaClient:rotate', {
      'args': { entries, direction } 
    });
  }
  async toggleStar(entries:object):Promise<any> {
    return this.emit('PicisaClient:toggleStar', {
      'args': { entries } 
    });
  }
  async getProjects(type:string):Promise<any> {
    return this.emit('PicisaClient:getProjects', {
      'args': { type } 
    });
  }
  async getContactAlbums():Promise<any> {
    return this.emit('PicisaClient:getContactAlbums', {
      'args': {  } 
    });
  }
  async getProject(project:object):Promise<any> {
    return this.emit('PicisaClient:getProject', {
      'args': { project } 
    });
  }
  async getProjectsCount(type:string):Promise<any> {
    return this.emit('PicisaClient:getProjectsCount', {
      'args': { type } 
    });
  }
  async writeProject(data:object, changeType:string):Promise<any> {
    return this.emit('PicisaClient:writeProject', {
      'args': { data, changeType } 
    });
  }
  async getFaceDataFromAlbumEntry(entry:object):Promise<any> {
    return this.emit('PicisaClient:getFaceDataFromAlbumEntry', {
      'args': { entry } 
    });
  }
  async createProject(type:string, name:string):Promise<any> {
    return this.emit('PicisaClient:createProject', {
      'args': { type, name } 
    });
  }
  async histogram(context:string):Promise<any> {
    return this.emit('PicisaClient:histogram', {
      'args': { context } 
    });
  }
  async addBug(description:string):Promise<any> {
    return this.emit('PicisaClient:addBug', {
      'args': { description } 
    });
  }
  async getBugs():Promise<any> {
    return this.emit('PicisaClient:getBugs', {
      'args': {  } 
    });
  }
  async getContacts():Promise<any> {
    return this.emit('PicisaClient:getContacts', {
      'args': {  } 
    });
  }
  async getFeatureFlags():Promise<any> {
    return this.emit('PicisaClient:getFeatureFlags', {
      'args': {  } 
    });
  }
  async updateFeatureFlags(flags:object):Promise<any> {
    return this.emit('PicisaClient:updateFeatureFlags', {
      'args': { flags } 
    });
  }
}