import { Contact } from "../../../shared/types/types";
import { Album } from "../../../shared/types/types";
import { AlbumEntryMetaData } from "../../../shared/types/types";
import { AlbumEntry } from "../../../shared/types/types";

/* This file is automatically generated, do not edit it */
/* This file is generated from the template located here : /Users/turpault/dev/picisa/server/rpc */

export class WalkerWorkerClient {
  private transport_?: any;
  initialize(transport: any): void {
    this.transport_ = transport;
  }

  public on(event: string, cb: Function): Function {
    return this.transport_.on(event, cb);
  }

  // @ts-ignore
  private async emitNoPayload(command: string, payload: any): Promise<void> {
    return this.emit(command, payload);
  }

  private async emit(command: string, payload: any): Promise<any> {
    return new Promise((resolve, reject) =>
      this.transport_.emit(command, payload, (error:string, response:string) => {
        if (error) {
          reject(error);
        } else {
          resolve(response);
        }
      })
    );
  }

  async updateEntryMetadata(entry:object, fieldOrMetadata:any, value?:any):Promise<any> {
    return this.emit('WalkerWorkerClient:updateEntryMetadata', {
      'args': { entry, fieldOrMetadata, value } 
    });
  }
  async setCaption(entry:object, caption:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setCaption', {
      'args': { entry, caption } 
    });
  }
  async setFilters(entry:object, filters:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setFilters', {
      'args': { entry, filters } 
    });
  }
  async setRotate(entry:object, rotate?:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setRotate', {
      'args': { entry, rotate } 
    });
  }
  async toggleStar(entries:object):Promise<any> {
    return this.emit('WalkerWorkerClient:toggleStar', {
      'args': { entries } 
    });
  }
  async rotate(entries:object, direction:string):Promise<any> {
    return this.emit('WalkerWorkerClient:rotate', {
      'args': { entries, direction } 
    });
  }
  async updateAlbumShortcut(album:object, shortcut:string):Promise<any> {
    return this.emit('WalkerWorkerClient:updateAlbumShortcut', {
      'args': { album, shortcut } 
    });
  }
  async touchPicasaEntry(entry:object):Promise<any> {
    return this.emit('WalkerWorkerClient:touchPicasaEntry', {
      'args': { entry } 
    });
  }
  async refreshAlbumKeys(albumKeys:object):Promise<any> {
    return this.emit('WalkerWorkerClient:refreshAlbumKeys', {
      'args': { albumKeys } 
    });
  }
  async refreshAlbums(albums:object):Promise<any> {
    return this.emit('WalkerWorkerClient:refreshAlbums', {
      'args': { albums } 
    });
  }
  async onRenamedAlbums(from:object, to:object):Promise<any> {
    return this.emit('WalkerWorkerClient:onRenamedAlbums', {
      'args': { from, to } 
    });
  }
  async reindexAlbums(albumIds:object):Promise<any> {
    return this.emit('WalkerWorkerClient:reindexAlbums', {
      'args': { albumIds } 
    });
  }
  async getPicasaIdentifiedReferences(entry:object):Promise<any> {
    return this.emit('WalkerWorkerClient:getPicasaIdentifiedReferences', {
      'args': { entry } 
    });
  }
  async getAlbumPicasaContactByHash(album:object, hash:string):Promise<any> {
    return this.emit('WalkerWorkerClient:getAlbumPicasaContactByHash', {
      'args': { album, hash } 
    });
  }
}