import { Album } from "../../../shared/types/types";
import { AlbumEntryMetaData } from "../../../shared/types/types";
import { AlbumEntry } from "../../../shared/types/types";

/* This file is automatically generated, do not edit it */
/* This file is generated from the template located here : /Users/turpault/dev/picisa/server/rpc */

export class WalkerWorkerClient {
  private transport_?: any;
  async initialize(socket: any): Promise<void> {
    this.transport_ = socket;
  }

  public on(event: string, cb: Function): Function {
    return this.transport_.on(event, cb);
  }

  // @ts-ignore
  private async emitNoPayload(command: string, payload: any): Promise<void> {
    return this.emit(command, payload);
  }

  private async emit(command: string, payload: any): Promise<any> {
    return new Promise((resolve, reject) =>
      this.transport_.emit(command, payload, (error:string, response:string) => {
        if (error) {
          reject(error);
        } else {
          resolve(response);
        }
      })
    );
  }

  async updateEntryMetadata(entry:object, metadata:object):Promise<any> {
    return this.emit('WalkerWorkerClient:updateEntryMetadata', {
      'args': { entry, metadata } 
    });
  }
  async updatePicasaEntry(entry:object, field:string, value:any):Promise<any> {
    return this.emit('WalkerWorkerClient:updatePicasaEntry', {
      'args': { entry, field, value } 
    });
  }
  async setCaption(entry:object, caption:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setCaption', {
      'args': { entry, caption } 
    });
  }
  async setFilters(entry:object, filters:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setFilters', {
      'args': { entry, filters } 
    });
  }
  async setRotate(entry:object, rotate?:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setRotate', {
      'args': { entry, rotate } 
    });
  }
  async toggleStar(entries:object):Promise<any> {
    return this.emit('WalkerWorkerClient:toggleStar', {
      'args': { entries } 
    });
  }
  async rotate(entries:object, direction:string):Promise<any> {
    return this.emit('WalkerWorkerClient:rotate', {
      'args': { entries, direction } 
    });
  }
  async setPicasaAlbumShortcut(album:object, shortcut:string):Promise<any> {
    return this.emit('WalkerWorkerClient:setPicasaAlbumShortcut', {
      'args': { album, shortcut } 
    });
  }
  async touchPicasaEntry(entry:object):Promise<any> {
    return this.emit('WalkerWorkerClient:touchPicasaEntry', {
      'args': { entry } 
    });
  }
}