const stringTable: { [key: string]: any } = {
  "Play slideshow": { fr: "Lecture" },
  Shortcut: { fr: "Raccourci" },
  "Unknown date": { fr: "Date inconnue" },
  "Open in Finder": { fr: "Ouvrir dans le Finder" },
  "Icon Size": { fr: "Taille des Icones" },
  Undo: { fr: "Annuler" },
  Browser: { fr: "Photothèque" },
  "Export Favorites": { fr: "Exporter les meilleures photos" },
  "View starred only": { fr: "Seulement les meilleures photos" },
  "View videos only": { fr: "Seulement les videos" },
  "Export to folder": { fr: "Exporter..." },
  Duplicate: { fr: "Dupliquer" },
  "Move to new Album": { fr: "Déplacer vers un nouvel album..." },
  Rotate: { fr: "Rotation" },
  Mosaic: { fr: "Mosaique" },
  Delete: { fr: "Effacer" },
  "Move $1 files to $2...": { fr: "Déplacer $1 fichier vers $2..." },
  "Rename album $1 to $2": { fr: "Renommer l'album de $1 vers $2..." },
  File: { fr: "Fichier" },
  Map: { fr: "Plan" },
  Metadata: { fr: "Données" },
  "Delete Album": { fr: "Effacer l'album" },
  "Edit Album Name": { fr: "Modifier le nom de l'album" },
  Crop: { fr: "Recadrer" },
  "Crop Picture": { fr: "Recadrer la photo" },
  "Crop Details": {
    en: "Select a dimension below and drag the pointer over the image to select the part to crop.",
    fr: "Sélectionnez une dimension ci-dessous et faites glisser le pointeur sur l'image pour sélectionner la partie à recadrer.",
  },
  Tilt: { fr: "Redresser" },
  Autocolor: { fr: "Couleur auto" },
  Greyscale: { fr: "Noir et blanc" },
  Contrast: { fr: "Contraste" },
  Brightness: { fr: "Luminosité" },
  Highlights: {fr:"Lumières"},
  Sepia: { fr: "Sépia" },
  Polaroid: { fr: "Polaroid" },
  Flip: { fr: "Inverser" },
  Mirror: { fr: "Miroir" },
  Blur: { fr: "Flou" },
  Sharpen: { fr: "Piqué" },
  "Extra Light": { fr: "Lumiere d'appoint" },
  "Original Date": { fr: "Date de l'original" },
  "Width (pixels)": { fr: "Largeur (pixels)" },
  "Height (pixels)": { fr: "Hauteur (pixels)" },
  Make: { fr: "Marque" },
  Model: { fr: "Modele" },
  ISO: { fr: "ISO" },
  "Exposure Time": { fr: "Temps d'exposition" },
  "F-Number": { fr: "Ouverture (F-Number)" },
  "Sort by Name": { fr: "Trier par nom" },
  "Sort by Date": { fr: "Trier par date" },
  "Reverse Sort": { fr: "Inverser le tri" },
  "No description": { fr: "Aucune description" },
  Effects: { fr: "Effets" },
  Album: { fr: "Album" },
  "Export All Favorites": { fr: "Exporter les préférées" },
  "Export selection to folder": { fr: "Exporter la sélection" },
  "Export displayed image to folder": { fr: "Exporter l'image affichée" },
  "Clone Selection": { fr: "Cloner la selection" },
  "Move selection to new Album": {
    fr: "Déplacer la selection vers un nouvel album",
  },
  "Add/Remove favorite": { fr: "Ajouter/Enlever des préférées" },
  "Rotate Selected Left": { fr: "Tourner l'image a gauche" },
  "Rotate Selected Right": { fr: "Tourner l'image a droite" },
  "Create Mosaic": { fr: "Créer une mosaique" },
  "Create Slideshow": { fr: "Créer une animation" },
  "Nothing to undo": { fr: "Rien a annuler" },
  "Select shortcut for this folder": {
    fr: "Sélectionner le raccourci pour cet album",
  },
  project: { fr: "Projets", en: "Projects" },
  Description: { fr: "Description" },
  "photos selected": { fr: "photos sélectionnées" },
  "More...": { fr: "Plus..." },
  "Do you want to delete $1 files": { fr: "Voulez-vous effacer $1 fichiers" },
  "Delete $1 files...": { fr: "Effacer $1 fichier..." },
  faces: { fr: "Personnes", en: "People" },
  shortcuts: { fr: "Raccourcis", en: "Shortcuts" },
  folders: { fr: "Dossiers", en: "Folders" },
  "Only Videos": { fr: "Videos Seulement" },
  "Show/Hide Identification": { fr: "Montrer/Cacher les identifications" },
  Identify: { fr: "Identifier" },
  "Only Favorites": { fr: "Seulement les préférées" },
  "Mosaic Parameters": { fr: "Parametres de la Mosaique" },
  Square: { fr: "Carré" },
  None: { fr: "Aucun" },
  Small: { fr: "Petite" },
  Medium: { fr: "Moyenne" },
  Large: { fr: "Grande" },
  Portrait: { fr: "Portrait" },
  Paysage: { fr: "Paysage" },
  "Target Size": { fr: "Taille de l'image" },
  "Gutter Size": { fr: "Taille de la marge" },
  Actions: { fr: "Actions" },
  Shuffle: { fr: "Mélanger" },
  "Import Selection": { fr: "Importer la sélection" },
  "Make Image": { fr: "Créer une image" },
  "Image List": { fr: "Liste d'images" },
  Width: { fr: "Largeur" },
  Height: { fr: "Hauteur" },
  Size: { fr: "Taille" },
  Modified: { fr: "Modifié" },
  Changed: { fr: "Changé" },
  Created: { fr: "Créé" },
  Cancel: { fr: "Annuler" },
  Adjustments: { fr: "Ajustements" },
  Reset: { fr: "Annuler" },
  Modify: { fr: "Modifier" },
  "Rotate Left": { fr: "Tourner à gauche" },
  "Rotate Right": { fr: "Tourner à droite" },
  "Export $1 item(s)": { fr: "Exporter $1 elements(s)" },
  "Duplicate $1 item(s)": { fr: "Dupliquer $1 elements(s)" },
  "Move $1 item(s) to a new album": {
    fr: "Déplacer $1 elements(s) vers un nouvel album",
  },
  "Delete $1 item(s)": { fr: "Supprimer $1 elements(s)" },
  Histogram: { fr: "Histogramme" },
  "Ctrl+D": { fr: "Ctrl+D" },
  Space: { fr: "Espace" },
  "Ctrl+ArrowLeft": { fr: "Ctrl+FlecheGauche" },
  "Ctrl+ArrowRight": { fr: "Ctrl+FlecheDroite" },
  "Ctrl+Z": { fr: "Ctrl+Z" },
  Move: { fr: "Déplacement" },
  "New album": { fr: "Nouvel album" },
  Filters: { fr: "Filtres" },
  "Back to Photo Library": { fr: "Retour a la Photothèque" },
  "▶ Play": { fr: "▶ Jouer" },
  Ok: { fr: "Ok" },
  "Histogram data and informations about the camera": {
    fr: "Histogramme et informations sur l'appareil",
  },
  "Export...": { fr: "Exporter..." },
  Slideshow: { fr: "Slideshow" },
  Finder: { fr: "Finder" },
  location: { fr: "Position" },
  metadata: { fr: "Propriétés" },
  "Size (pixels)": { fr: "Taille (pixels)" },
  Ratio: { fr: "Ratio" },
  Orientation: { fr: "Orientation" },
  Apply: { fr: "Appliquer" },
  of: { fr: "sur" },
  persons: { fr: "Personnes", en: "People" },
  "4x6": { fr: "4x6" },
  "5x7": { fr: "5x7" },
  "8x10": { fr: "8x10" },
  "4x3": { fr: "4x3" },
  "16x9": { fr: "16x9" },
  "5x5": { fr: "5x5" },
  Free: { fr: "Libre" },
  portrait: { fr: "Portrait" },
  paysage: { fr: "Paysage" },
  "Not implemented yet": { fr: "Pas de panique Tab..." },
  Heatmap: { fr: "Heatmap" },
  Solarize: { fr: "Solarisation" },
  "Apply a blur with a specific radius": {
    fr: "Applique un flou avec un rayon spécifique",
  },
  Filter: { fr: "Filtre" },
  "iPhoto Favorites": { fr: "Favoris iPhoto" },
  "Import Favorites from Photo app": {
    fr: "Importer les favoris de l'app Photos",
  },
  "Redo": {fr:"Refaire", en:"Redo"},
  "Rotate the image": {fr:"Tourner l'image"} ,
  "": {fr:""},
  "Amount": {fr:"Quantité"},
  "Loading bugs...": {fr:"Chargement des bugs..."},
"open": {fr:"ouvert", "en":"open"},
"What is the bug?": {fr:"Quel est le bug?"},
"Describe the bug": {fr:"Décrivez le bug"},
};
const lang = window.navigator.language.split("-")[0];
let str = new Set<string>();
export function t(s: string, ...args: any[]): string {
  const sp = s.split("|");
  if (sp.length > 1) return t(sp[0], ...sp.slice(1), ...args);

  let res = stringTable[s]?.[lang];
  if (res === undefined) {
    if (lang !== "en") {
      str.add(`"${s}": {fr:"${s}"},`);
      console.log("Missing strings", Array.from(str).join("\n"));
    }
    res = s;
  }
  // Replace positional arguments
  if (args.length > 0) {
    args.forEach((v, idx) => (res = res.replace(`$${idx + 1}`, v)));
  }
  return res;
}
